### ISSUE TITLE
create dependabot.yml file to bump vulnerable dependencies

### ISSUE THREAD

**Issue by the-gigi** [the-gigi/wod-craft-server#4]
This is a Python project, so should be something like:

```
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
```
